name: print-name

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  print_name_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Print Name
        run: echo "Hello from print-name workflow!"
